description: 'Banigama is the village in madhubani district of bihar. Banigama is the first village in bihar which have own website.
              Banigama is village in India. Indian village'
url: 'banigama.com'
author: 'Mihir Kumar Thakur'
email: 'contact@banigama.com'
keywords: "banigama, village With website, Website village, banigama With website, madhubani district village indian village bihar village gaon tola muhalla banigama gaon banigama village"

gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
